[package]
name = "mediaforge-storage"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
aws-config.workspace = true
aws-credential-types.workspace = true
aws-sdk-s3.workspace = true
aws-types.workspace = true
bytes.workspace = true
mediaforge-config = { path = "../mediaforge-config" }
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
tempfile.workspace = true

